server:
  port: 8083
spring:
  application:
    name: entityService



  datasource:
    url: jdbc:h2:mem:mydb
    username: book
    password: 1234
    driverClassName: org.h2.Driver
  main:
    allow-circular-references: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

    defer-datasource-initialization=true:

  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost
